application: kenkjw-udacity-fsnd-p07
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/spi/.*
  script: battleships.api
  secure: always

- url: /crons/send_reminder
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: endpoints
  version: latest

- name: pycrypto
  version: latest